### ISSUE TITLE
DEBUG: Missing mandatory parameter

### ISSUE THREAD

**Issue by andyxm715** [mason362/studio66tv#2]
Hi,

trying to use your Studio66 downloader, I have changed the ini file for my setup but keep getting a DEBUG: Missing mandatory parameter(s). Exiting... error, I have gotten your Babestation doownloader to work without any problems, could you confirm if its working ok for you.

Many Thanks

Andy

**Comment by thomasbg0184** [comment]
hi, did you sort this? if so, can i ask how?

**Comment by andyxm715** [comment]
yes for the studio 66 script you need to run the script as ./s66tv-record-sl.sh 1 DayShow ./s66tv-record-sl.sh 2 DayShow and so on for each stream as well as ./s66tv-record-sl.sh 1 NightShow for streams after 10pm

**Comment by thomasbg0184** [comment]
hi thanks for the reply, i'm totally new to this, can you PM me on the liveshow forum please? i have posted in the stream to vlc thread asking if you could turn your PMs on? would appreciate it, username is tom1260

**Comment by thomasbg0184** [comment]
if not that then is there another way to talk privately please?
